export const characters = {
  home: {
    name: 'Fantastic Four',
    tagline: 'Heroes Unite',
    heroClass: 'theme-home',
    navText: 'Home',
    icon: 'fa-solid fa-fire',
    members: [
      { key: 'reed', name: 'Mr. Fantastic', icon: 'fa-solid fa-arrows-left-right', desc: 'Brilliant scientist and elastic leader.' },
      { key: 'sue', name: 'Invisible Woman', icon: 'fa-solid fa-eye-slash', desc: 'Master of invisibility and force fields.' },
      { key: 'johnny', name: 'Human Torch', icon: 'fa-solid fa-fire-flame-curved', desc: 'Flame on — the fiery hot-head of the team.' },
      { key: 'ben', name: 'The Thing', icon: 'fa-solid fa-mountain', desc: 'Rock-solid powerhouse with a heart of gold.' },
    ],
    stats: [
      { label: 'Years Active', value: '60+', icon: 'fa-solid fa-calendar-days' },
      { label: 'Villains Defeated', value: '500+', icon: 'fa-solid fa-shield-halved' },
      { label: 'Baxter Building', value: 'HQ', icon: 'fa-solid fa-building' },
      { label: 'Galactus Fights', value: '12', icon: 'fa-solid fa-globe' },
    ],
  },
  reed: {
    name: 'Mr. Fantastic',
    realName: 'Reed Richards',
    tagline: 'Stretch Beyond Limits',
    heroClass: 'theme-reed',
    navText: 'Mr. Fantastic',
    icon: 'fa-solid fa-arrows-left-right',
    primary: '#2563eb',
    accent: '#60a5fa',
    font: "'Rubik', sans-serif",
    powers: [
      { name: 'Elasticity', icon: 'fa-solid fa-expand', level: 100 },
      { name: 'Genius Intellect', icon: 'fa-solid fa-brain', level: 98 },
      { name: 'Shape-shifting', icon: 'fa-solid fa-shapes', level: 90 },
      { name: 'Leadership', icon: 'fa-solid fa-users-gear', level: 85 },
    ],
    bio: 'Reed Richards is one of the most brilliant minds in the Marvel Universe. Exposed to cosmic rays during an experimental space voyage, he gained the ability to stretch his body into any shape imaginable. As the leader of the Fantastic Four, Reed combines his superhuman elasticity with an unmatched intellect to solve problems no other hero can.',
    quote: 'The greatest discoveries often come from the most unexpected places.',
    abilities: [
      { icon: 'fa-solid fa-ruler-horizontal', title: 'Elongation', text: 'Can stretch any part of his body up to 3 miles.' },
      { icon: 'fa-solid fa-glasses', title: 'Master Inventor', text: 'Creator of the Unstable Molecule suits and the Fantasti-Flare.' },
      { icon: 'fa-solid fa-hammer', title: 'Grappling', text: 'Uses elastic limbs as ropes, bridges, and weapons.' },
      { icon: 'fa-solid fa-shield', title: 'Impact Absorption', text: 'Absorbs blows by cushioning them with flexible form.' },
    ],
  },
  sue: {
    name: 'Invisible Woman',
    realName: 'Sue Storm',
    tagline: 'Unseen Yet Unstoppable',
    heroClass: 'theme-sue',
    navText: 'Invisible Woman',
    icon: 'fa-solid fa-eye-slash',
    primary: '#7c3aed',
    accent: '#c4b5fd',
    font: "'Cinzel', serif",
    powers: [
      { name: 'Invisibility', icon: 'fa-solid fa-eye-slash', level: 100 },
      { name: 'Force Fields', icon: 'fa-solid fa-shield-halved', level: 95 },
      { name: 'Strategy', icon: 'fa-solid fa-chess-queen', level: 90 },
      { name: 'Leadership', icon: 'fa-solid fa-crown', level: 82 },
    ],
    bio: 'Sue Storm was exposed to cosmic rays alongside her teammates and gained the power to render herself invisible at will. Over time, her abilities evolved to include the creation of powerful invisible force fields, making her arguably the most powerful member of the Fantastic Four. She is the heart and strategic mind of the team.',
    quote: 'You don\'t need to be seen to make an impact.',
    abilities: [
      { icon: 'fa-solid fa-ghost', title: 'Total Invisibility', text: 'Bends light around herself and others completely.' },
      { icon: 'fa-solid fa-dome', title: 'Force Fields', text: 'Projects indestructible barriers of pure energy.' },
      { icon: 'fa-solid fa-bolt', title: 'Force Bolts', text: 'Launches invisible projectiles with concussive force.' },
      { icon: 'fa-solid fa-tower-observation', title: 'Tactical Mind', text: 'Often the field strategist during missions.' },
    ],
  },
  johnny: {
    name: 'Human Torch',
    realName: 'Johnny Storm',
    tagline: 'Flame On',
    heroClass: 'theme-johnny',
    navText: 'Human Torch',
    icon: 'fa-solid fa-fire-flame-curved',
    primary: '#dc2626',
    accent: '#fb923c',
    font: "'Audiowide', sans-serif",
    powers: [
      { name: 'Pyrokinesis', icon: 'fa-solid fa-fire', level: 100 },
      { name: 'Flight', icon: 'fa-solid fa-feather', level: 92 },
      { name: 'Heat Resistance', icon: 'fa-solid fa-temperature-high', level: 95 },
      { name: 'Nova Blast', icon: 'fa-solid fa-explosion', level: 88 },
    ],
    bio: 'Johnny Storm is the youngest member of the Fantastic Four and the thrill-seeker of the group. When cosmic rays gave him the ability to engulf his body in flame, he became the Human Torch. With the power of flight, fire manipulation, and nova-level heat output, Johnny is as hot-headed as he is heroic.',
    quote: 'When things get tough, the tough get flamin\'!',
    abilities: [
      { icon: 'fa-solid fa-fire', title: 'Body Flame', text: 'Engulfs his entire body in superheated plasma fire.' },
      { icon: 'fa-solid fa-jet-fighter-up', title: 'Supersonic Flight', text: 'Flies at speeds up to Mach 5 using thermal updrafts.' },
      { icon: 'fa-solid fa-bomb', title: 'Nova Blast', text: 'Releases all stored energy in a single massive explosion.' },
      { icon: 'fa-solid fa-meteor', title: 'Fireball Projection', text: 'Hurls concentrated fireballs with pinpoint accuracy.' },
    ],
  },
  ben: {
    name: 'The Thing',
    realName: 'Ben Grimm',
    tagline: 'It\'s Clobberin\' Time',
    heroClass: 'theme-ben',
    navText: 'The Thing',
    icon: 'fa-solid fa-mountain',
    primary: '#d97706',
    accent: '#fbbf24',
    font: "'Russo One', sans-serif",
    powers: [
      { name: 'Super Strength', icon: 'fa-solid fa-dumbbell', level: 100 },
      { name: 'Rock Skin', icon: 'fa-solid fa-mountain', level: 98 },
      { name: 'Durability', icon: 'fa-solid fa-shield', level: 95 },
      { name: 'Combat Skill', icon: 'fa-solid fa-hand-fist', level: 80 },
    ],
    bio: 'Ben Grimm was Reed Richards\' college roommate and best friend. After the cosmic ray incident, Ben was transformed into a creature with skin made of orange rock, granting him incredible strength and near-invulnerability. Despite his fearsome appearance, Ben has the biggest heart on the team and is fiercely loyal to his family.',
    quote: 'It\'s clobberin\' time!',
    abilities: [
      { icon: 'fa-solid fa-dumbbell', title: 'Class 100 Strength', text: 'Can lift over 100 tons with raw physical power.' },
      { icon: 'fa-solid fa-shield-halved', title: 'Rock Armor', text: 'His stone skin resists bullets, lasers, and explosions.' },
      { icon: 'fa-solid fa-hand-fist', title: 'Street Fighting', text: 'A seasoned brawler with decades of hand-to-hand combat.' },
      { icon: 'fa-solid fa-heart', title: 'Unbreakable Will', text: 'Never gives up — loyalty is his greatest strength.' },
    ],
  },
};

export const navItems = ['home', 'reed', 'sue', 'johnny', 'ben'];
